### ISSUE TITLE
Covered Options Dialog on Web UI - 2.031 (and older)

### ISSUE THREAD

**Issue by karstenthiemann** [volumio/Volumio2-UI#248] opened 2016-12-03 16:29 UTC
The options dialog gets covered by the search area on top of the web ui so you can't select play/add to queue/clear and play options. This problem occurs on displays with lower resolutions like the official raspberry 7'' touch display and on mobile phones (mobile firefox and chrome).
The options dialog for second row entries in the browse tab is shown on top of the entry because there is not enough space to show it under the entry ending in a dialog hidden by the search area.

Suggested solution: bring the dialog div always to the top (z-index) or set the min top position of the dialog to the lower corner of the search area

**Comment by fiodoro** [comment] 2018-12-15 14:09
Any news on this? Seems to be the same as #524. Also described in https://volumio.org/forum/raspberry-touchscreen-context-menu-not-accessible-t8437.html#p43192.

I'm expieriencing this bug with german locale on the official raspberry 7" touch display and on my tablet. But there only with the chrome browser. Firefox works well. So maybe this issue is related to the chromium engine, which is also use by the touch display plugin?

**Comment by geek-merlin** [comment] 2020-01-13 12:43
It looks like this is a 100% duplicate of #524 ?

**Comment by xipmix** [comment] 2020-01-14 10:56
I thought this had been fixed. Have you (or anyone) been able to reproduce it?

**Comment by geek-merlin** [comment] 2020-01-14 15:04
See #524

**Closed** 2020-03-12 22:35 UTC
