### ISSUE TITLE
Why are Facebook SDK / Google Analytics necessary?

### ISSUE THREAD

**Issue by dmth** [volumio/Volumio2-UI#415] opened 2017-10-12 12:12 UTC
Hey guys,
First of all thank you very much for maintaining and creating this great piece of software.

I'm wondering why the Facebook SDK and Google Analytics are necessary:

https://github.com/volumio/Volumio2-UI/blob/master/src/index.html#L77

Everytime I open the GUI in my Browser, a connection is made to facebook.

I guess it might be required for the "[follow-wizard](https://github.com/volumio/Volumio2-UI/blob/b51ffdaf3bbe2f406ac7b425086596cd2f1eb978/src/app/wizard/views/wizard-follow.html)", but I'm not sure here. 
Might it be possible to limit the loading of the sdk to the point in time were the wizard is run?

BR
Dustin

**Comment by volumio** [comment] 2017-10-13 11:33
Hi Dustin, you're right. We will do the changes

**Comment by dmth** [comment] 2017-10-15 16:59
Thanks, I'm looking forward to it.

**Comment by kehugter** [comment] 2017-10-17 21:13
See also #310.

I'll run a patched `dist` branch from now on. https://github.com/kehugter/Volumio2-UI

**Comment by volumio** [comment] 2017-10-17 22:13
@kehugter ah, instead of giving something back by contributing an opt out mechanism, you just create your own version... kudos

**Comment by kehugter** [comment] 2017-10-18 22:12
> instead of giving something back

I've given back monetarily, promoting Volumio / Volumio shop and by trying to implement #310.

> just create your own version

More a workaround than my own version.

As for #310: Google's opt-out is a joke. The whole tracking still runs, you just have to hope that they'll keep their word and not send data back. Removing GA completely would have needed, in my opinion, a different UI build anyway, like I did in the `dist-privacy` branch. The user can then put a placeholder in `/boot` (similar to enabling ssh) to switch the branch for the UI during the first boot.

**Comment by volumio** [comment] 2017-10-18 22:33
Could we dynamically load the analytics js? The issue here is to store such info on the BE and notify the FE whether to load the library or not... Ideas?

**Comment by kehugter** [comment] 2017-10-20 19:30
> Could we dynamically load the analytics js?

I don't know. I read a few days ago that GA doesn't like to be called from iframes, but nothing about dynamic loading. Shouldn't be a problem I guess.

> Ideas?

Can we set an opt-out cookie via settings and load the tracking scripts only is that cookie is missing? That solution would require less maintenance and changes in the build process than the idea with different git branches.

Another shot: build 2 different `http/www/index.html`, one with tracking and one without. The webserver decides which one to use depending on a placeholder like the `/boot/ssh` one. This solution is not nearly as clean as the previous one, and I doubt that there are any noticeable performance differences.

**Comment by volumio** [comment] 2017-10-20 22:37
I think we have 2 starting points:
- The setting must be stored on BE for persistence of the choice among all FEs
- We need to dynamically load the library based on such choice, therefore we need to change where the library gets loaded (hopefully it will still work when enabled) and find a way to retrieve the setting while not causing performance bottlenecks...

Would you be willing to help on the second one while I take care of the first?

**Comment by kehugter** [comment] 2017-10-21 20:08
> Would you be willing to help on the second one while I take care of the first?

Sure!

**Comment by opnwrt4lede** [comment] 2017-12-08 13:43
Quick workaround is to blacklist the following domains in your firewall or local dns:

- connect.facebook.net
- google-analytics.com

I think browser addons like ublock origin or noscript are not sufficient because volumio tries to call third parties (in US and Ireland) without calling the webserver, correct?

**Comment by volumio** [comment] 2017-12-08 14:11
Removed FB SDK with https://github.com/volumio/Volumio2-UI/pull/450/commits/a2516a80c88fdf90e7679a533b269ac8ad8a8a48

**Comment by opnwrt4lede** [comment] 2017-12-09 10:32
Thank's @volumio
Is there anything reasonable what we do against google?

**Comment by dmth** [comment] 2017-12-09 16:47
@volumio thank you for removing the facebook sdk.

Why is google-analytics necessary?

**Comment by volumio** [comment] 2017-12-10 14:01
@dmth this is a good explanation of why we use it in Volumio, which data we care and what we do with it:
https://github.com/volumio/Volumio2-UI/issues/310#issuecomment-298340598

Putting it short, it helps us a lot to understand the typical usage scenario and we make development decisions based on this data. The only goal of it is to make Volumio better.

**Comment by pidiet** [comment] 2018-02-05 10:48
I would also would like to see a google-free version of volumio!

**Comment by volumio** [comment] 2018-02-05 10:50
Working on it:
https://github.com/volumio/Volumio2-UI/tree/ga-opt-out

**Comment by pidiet** [comment] 2018-02-05 10:51
@volumio great to hear that! Thank you for all your work!

**Comment by sploinga** [comment] 2018-05-20 21:07
Can I know if this issue has been/is being solved ? As an end user, I wanted to install volumio, but seeing that there was an embedded google tracking discouraged me. Nonetheless volumio seems to be one of the most active projects and I like the ui. If there was an opt-out, i'd switch to it  quickly.

**Comment by volumio** [comment] 2018-05-22 12:37
@sploinga FB SDK has been removed, and the opt-in works for GA started in december, but due to lack of time I wasn't able to complete it yet

**Comment by sploinga** [comment] 2018-05-22 12:48
@volumio Thanks for your answer! Anything I could do ? I don't read javascript but I can understand html and yaml files. Maybe with pointers I could work on it.

**Comment by ssixty** [comment] 2018-11-01 15:54
I just installed VolumeIO and was disappointed to find its web interface contacting google analytics, as well as something called Paddle.com.

Regardless of privacy policy,  the first setup page would ideally clearly explain your reasons to include such tracking before any requests are made to those third-parties and either an opt-in or a full and persistant opt-out.

Thanks for beginning work on opt-out for google analytics.   I didn't see any mention of Paddle in the issues here,  what is it being used for? Will you include it in the opt-out?

**Comment by volumio** [comment] 2018-11-02 14:51
Facebook has been removed. Firebase is necessary for MyVolumio (user management and real time database, and will only been enabled if you login in myvolumio) paddle is our payment system provider (which again will be enabled only when you pay). So, they can't be included in opt out because without them MyVolumio won't work, and if you don't use MyVolumio they just do nothing

**Comment by ssixty** [comment] 2018-11-03 12:56
Thanks for explaining their purpose.  I understand that their javascript might not be executed without using the myvolumio or payment features but the issue still stands that it's being loaded from these third parties in the first place. 

Here's the requests made when I view the initial setup screen on a freshly installed volumio:
https://cdn.paddle.com/paddle/paddle.js
https://myvolumio.firebaseio.com/.lp?start=t&ser=96577229&cb=3&v=5  (this keeps retrying with different query string values every few seconds)
https://www.google-analytics.com/analytics.js

So paddle/firebase/google just received my IP, browser information, the local network IP of my Pi, etc. This seems unnecessary, could the paddle/firebase .js only be loaded when you're at the point of paying or logging in/already having logged in?

**Comment by ying-w** [comment] 2018-11-21 23:13
removing google-analytics from index.html is simple enough, any tips on removing myvolumio/paddle?

**Comment by buzuck** [comment] 2018-12-29 19:57
I totally agree with that issue. Volumio shouldn't be relying on external sources :
 * MyVolumio shouldn't try to connect to anywhere unless asked for
 * Other needed libraries should be embedded within the Volumio image

Those "details" are susceptible to make me move away from Volumio... :disappointed:  :angry:

**Comment by smartroad** [comment] 2018-12-30 13:39
> How did you do that? Just removing the reference to it in `/volumio/http/www/index.html` doesn't do the job here.

Could it be loading a cached version? I deleted it and it went away (at least it stopped the error report that it couldn't contact google because I block it anyway).

Out of interest, under GDPR do you not have to provide the ability to opt-out? What about sending it to 3rd party services? My company we have to ask before sending data to a 3rd party service.

**Comment by buzuck** [comment] 2019-01-03 23:31
> Could it be loading a cached version?
Correct. My bad. I remember hitting `CTRL + F5` though, that is supposed to skip the cache...
> Out of interest, under GDPR do you not have to provide the ability to opt-out?
I'm not a specialist, but sounds legit :-)

**Comment by mulle12** [comment] 2019-02-26 14:57
It seems, volumio needs a google account to work.

I have two android-phones, a Samsung with all the google stuff, and a Motorola g4-play which I did set up without a google-account. 

I made a new installation of volumio to the raspberry pi without LAN. This creates the hotspot "volumio".

Connecting the Samsung to the hotspot, the UI was immediately displayed via  http://volumio.local.

On the Motorola this did not work. It connected to the hotspot, but neither  http://volumio.local nor 192.168.211.1 brought up the UI. Instead it said: 

net::ERR_NAME_NOT_RESOLVED

Some additional information: I never subscribed to MyVolumio. The Motorola is a 4G-Play with Android 7.1.1. After some juggling I reached the UI once, but the url was

http://connectivitycheck.gstatic.com

and there appeared a note urging me to connect to my network. I declined, and voluminos UI disappeared. According to Wikipedia, connectivitycheck is an android captive portal.

It seems, that volumio is like the other google services, needing a google account to function.

**Comment by volumio** [comment] 2019-02-26 15:07
No, you're wrong. Having a google account is not mandatory and it's not related to the issues you provide.

You can't reach it from your motorola phone since it does not handle mdns discovery. In such cases you should always use the Raspberry IP address

**Comment by mulle12** [comment] 2019-02-26 22:03
It seems, volumio needs a google account to work.

I have two android-phones, a Samsung with all the google stuff, and a Motorola g4-play which I did set up without a google-account. 

I made a new installation of volumio to the raspberry pi without LAN. This creates the hotspot "volumio".

Connecting the Samsung to the hotspot, the UI was immediately displayed via  http://volumio.local.

On the Motorola this did not work. It connected to the hotspot, but neither  http://volumio.local nor 192.168.211.1 brought up the UI. Instead it said: 

net::ERR_NAME_NOT_RESOLVED

Some additional information: I never subscribed to MyVolumio. The Motorola is a 4G-Play with Android 7.1.1. After some juggling I reached the UI once, but the url was

http://connectivitycheck.gstatic.com

and there appeared a note urging me to connect to my network. I declined, and voluminos UI disappeared. According to Wikipedia, connectivitycheck is an android captive portal.

It seems, that volumio is like the other google services, needing a google account to function.

**Comment by mulle12** [comment] 2019-02-26 22:05
Volumio, thank you for your rapid answer. Your suggestion concerning raspberrie's ip is misleading, but you are right concerning the google account

With http://volumio.local the Samsung shows the UI as it should. But it does the same, if almost any other http-url is put into the browser; this is perhaps not so surprising, since we are in the strictly local environment without connection to the internet. 

Consider now the Motorola. As stated prevously, volumio.local does not work, and also the ip of the hotspot just generates a blank screen.

However, I overlooked that the two phones differed in another respect. The Motorola had a sim card and the Samsung had none. If the sim card is removed, it works just like the Samsung. 

Conclusion: volumio works in the local hotspot, provided the sim cards are removed from the phone.

**Comment by buzuck** [comment] 2019-10-28 18:49
Duplicate of #310

**Comment by volumio** [comment] 2019-10-28 20:27
Closing this one, so we have one central point of discussion on https://github.com/volumio/Volumio2-UI/issues/310

**Closed by volumio** 2019-10-28 20:27 UTC
