### ISSUE TITLE
Mixer Control Name arbitrarily changes value

### ISSUE THREAD

**Issue by tbmsu** [volumio/Volumio2-UI#709] opened 2020-01-06 20:29 UTC
I use Volumio on a RPi 3 with a HifiBerry DAC Plus. Since the last update to version 2.692, the value of the setting "Mixer Control Name" sometimes arbitrarily changes from "Digital" to "Analogous". When this happens, I can no longer control the volume of the player. 

When I click on the drop-down menu it disappears (see #706). The only way to reset the value of "Mixer Control Name" back to its default (Digital) is to re-select the "DAC Model" in the section "Audio Output" and save the change.

Unfortunately I have not found out how to reproduce this behaviour, but I wanted to document it.

**Comment by xipmix** [comment] 2020-01-08 09:53
Thanks for the report.

This sounds a little bit like volumio/Volumio2/issues/1832 . The fix for that should be in the next release.

I think the disappearing drop-down menu may be a separate issue. Could you please send a [log](https://volumio.github.io/docs/User_Manual/Sending_logs_for_troubleshooting.html) of:
 * reboot
 * click on dropdown so it disappears (is this reproducible, or 'only happen sometimes'?)
 * reselect DAC Model and save

**Comment by tbmsu** [comment] 2020-01-08 18:27
Hi, here's the link to my log: http://logs.volumio.org/volumio/7NMqqle.html

After the reboot it happened again that the "Mixer Control Name" was reset to "Analogous" and the volume was set to 0. I reselected the DAC model and everything went back to normal. And yes, it's reproducible that the dropdown disappears. 

Hope this helps.

**Comment by xipmix** [comment] 2020-01-09 09:45
Here we go
```
Jan 08 18:18:37 volumio volumio[983]: info: Hardware Mixer selected but no Hardware mixer available, detecting default mixer
Jan 08 18:18:37 volumio volumio[983]: info: CoreCommandRouter::executeOnPlugin: i2s_dacs , getI2sStatus
Jan 08 18:18:37 volumio volumio[983]: info: Found match in Cards Database: setting mixer undefined for card HiFiBerry DAC Plus
Jan 08 18:18:37 volumio volumio[983]: info: Setting mixer Analogue for card HiFiBerry DAC Plus
```
This looks similar but not quite the same as issue 1832; nonetheless you don't want your ```alsa.outputdevicemixer``` being set to ```undefined```. If you want to try patching, you could try the _last_ version of  /volumio/app/plugins/audio_interface/alsa_controller/index.js in that issue, it contains just the fix. Be sure to copy the original so you can revert if necessary.
It may not fix your issue, please let us know, either way.

**Comment by tbmsu** [comment] 2020-01-09 20:00
Terrific! I copied the latest version of the file you mentioned to my device, did a few restarts and both errors (lost "mixer control name" and disappearing dropdown)  seem to be gone :)

**Comment by xipmix** [comment] 2020-01-10 10:44
ok cool - please can you close this when you have a second

**Comment by tbmsu** [comment] 2020-01-11 11:52
Issue is related to #1832 which is already fixed (or will be fixed with the next update).

**Closed** 2020-01-11 11:51 UTC

**Comment by tbmsu** [comment] 2020-03-15 09:56
Just a short notice on this: After the regular update to version 2.714, the above error is back again :( 

(of course I reverted the changes of index.js before, otherwise the updated fails)

**Comment by xipmix** [comment] 2020-03-16 12:31
Thanks, I shall try to reproduce when I've got a bit of time.

**Comment by volumio** [comment] 2020-03-16 12:44
@tbmsu can you provide more info please?

**Comment by volumio** [comment] 2020-03-17 00:34
> Just a short notice on this: After the regular update to version 2.714, the above error is back again :(
> 
> (of course I reverted the changes of index.js before, otherwise the updated fails)

This is what is causing your issue. Having manually edited and then reverted the file, created an inconsistency with the update. In fact, everything updated in the system except the file you manually edited (since you reverted to a non working file, this stayed).
Guess we need to make volumio dir readonly in order to avoid such situations (otherwise update will not be performed...)

**Comment by xipmix** [comment] 2020-03-17 08:52
Is it possible to do a 'cd /volumio; git reset --hard HEAD' ? I haven't looked at how the updater works, so this may not be the right approach.

**Comment by volumio** [comment] 2020-03-17 09:37
No, its not the right approach.
If a file gets updated or written (even with the same content), once an update is installed this file will stay as it has been written.
The solution here is to do a factory reset or delete user data and then update

**Comment by tbmsu** [comment] 2020-05-09 06:30
> The solution here is to do a factory reset or delete user data and then update

Sorry for the late reply, but yeah, that actually did the trick :)
